### ISSUE TITLE
User Story 1: Adding Products with the same name

### ISSUE THREAD

**Issue by paolostaana** [Ren149/INTROSE-Source-Repository#24]
Product will be treated as restock but Selling Price does not update.

**Comment by paolostaana** [comment]
Steps:
1. Select Add Product
2. Fill in all inputs with valid Inputs except for the Product Name
3. Input Product name as an existing Product
4. Press Add 
5. "Will be treated as restock" will show, select Yes.
6. Check Product list, notice that Selling Price did not update.

**Comment by nicorapisora** [comment]
Hasn't this been fixed already? Please check again.
