### ISSUE TITLE
User story 6: Refreshing product list after sale transaction

### ISSUE THREAD

**Issue by trixiecruz** [Ren149/INTROSE-Source-Repository#27]
The product list of the Sale tab does not automatically refresh after recording a sales transaction. It refreshes after the user switches to a different tab before switching back to the Sale tab. 

Steps to replicate the issue:
1. Open Sale tab
2. Select product1, add a quantity and click "Add to Cart" button
3. Click "Record" button
(In the product list, the quantity of product1 does not get deducted right after the sale transaction is made)
5. Open Product List tab
(The product list here is already updated)
6. Open Sale tab again 
(product1's quantity is now updated)

**Comment by trixiecruz** [comment]
I checked the sale tab again and the product list still does not automatically update after recording a sale transaction

**Comment by punzalan101** [comment]
fixed
