### ISSUE TITLE
User story 6: Sale transaction 

### ISSUE THREAD

**Issue by trixiecruz** [Ren149/INTROSE-Source-Repository#29]
When a product has two batches, the sold product's quantity is deducted from both batches.

Steps to recreate problem:
A. Restock product with a new batch (if there only exists one batch for Product1)
1. Open Product List tab 
2. Select Product1
3. Click "Restock" and enter a new batch

B. Recording a new sale transaction
1. Open Sale tab
2. Select Product1
3. Enter 10 in quantity then click "Add to Cart"
4. Click "Record"

C. Checking if Product1's quantity is deducted
1. Open Product List tab
2. Select Product1
The product is updated: 10 is deducted from each of Product1's batches

*\* Even if the batches have different lot numbers, the sale transaction still deducts the quantity from each batch

**Comment by trixiecruz** [comment]
P.S. Even if the batches have different lot numbers, the sale transaction still deducts the quantity from all batches

**Comment by punzalan101** [comment]
fixed
