### ISSUE TITLE
Discontinue Item - Batches are not emptied

### ISSUE THREAD

**Issue by nicorapisora** [Ren149/INTROSE-Source-Repository#36]
1. Add Product X.
2. Restock X to have multiple batches of it.
3. Discontinue X.
4. Add Product X again to set isDiscontinued to false.
5. Earlier batches are shown to still have quantities remaining.

Batches of a discontinued item should be emptied.

**Comment by paolostaana** [comment]
This is still an issue as of 8/24/2016 -- 12:00 AM
